### ISSUE TITLE
Decision tree model design

### ISSUE THREAD

**Issue by Chocotube** [Dianevera/heart-prediction#11]
Problem: We need to predict Death, ANYCHD, CVD, and HYPERTEN.
Solution: Implement a decision tree model to do the predictions.

**Comment by ninous-dev** [comment]
@Dianevera @Chocotube To review then merge

**Comment by Dianevera** [comment]
There are several useless comments (print) and unused variables (inputs, labels, columns in get_plit_value function ...) in the model file.
