### ISSUE TITLE
Package the DecisionTree

### ISSUE THREAD

**Issue by ninous-dev** [Dianevera/heart-prediction#15]
Probleme: DecisionTree class must be callable easily from any python file

Solution: Implement a package for the DecisionTree class

**Comment by ninous-dev** [comment]
Comments and decision tree package added directly by in dev by mistake.

Issue ready to be close @Chocotube @Dianevera

**Comment by Dianevera** [comment]
In the previous issues, we used Args instead of Parameters
There is an unused argument 'information_gain' and a TODO in the pretty_print_rec function

**Comment by ninous-dev** [comment]
@Dianevera Can you review this branch ?
